# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-08 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SampleApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emplyeetable',
            name='emp_exp',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='emplyeetable',
            name='emp_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
